import "~/styles/globals.css";

import { Bellefair, Barlow_Condensed, Barlow } from "next/font/google";
import Header from "./ui/header";

const bellefair = Bellefair({
  subsets: ["latin"],
  variable: "--font-bellefair",
  weight: ["400"],
});

const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  variable: "--font-barlow-condensed",
  weight: ["400"],
});

const barlow = Barlow({
  subsets: ["latin"],
  variable: "--font-barlow",
  weight: ["400"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${bellefair.variable} ${barlow.variable} ${barlowCondensed.variable} min-h-screen`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
